/**
 * Central error code registry. New error codes must be added here —
 * do not throw ad-hoc string codes anywhere else in the workspace.
 */
export enum ErrorCodes {
  // Generic
  UNKNOWN = 'CRYPTRA/UNKNOWN',
  VALIDATION_FAILED = 'CRYPTRA/VALIDATION_FAILED',
  NOT_FOUND = 'CRYPTRA/NOT_FOUND',
  UNAUTHORIZED = 'CRYPTRA/UNAUTHORIZED',
  FORBIDDEN = 'CRYPTRA/FORBIDDEN',
  RATE_LIMITED = 'CRYPTRA/RATE_LIMITED',
  CONFLICT = 'CRYPTRA/CONFLICT',

  // Wallet
  WALLET_NOT_CONNECTED = 'CRYPTRA/WALLET_NOT_CONNECTED',
  WALLET_PROVIDER_UNAVAILABLE = 'CRYPTRA/WALLET_PROVIDER_UNAVAILABLE',
  WALLET_CONNECTION_REJECTED = 'CRYPTRA/WALLET_CONNECTION_REJECTED',
  WALLET_ADDRESS_INVALID = 'CRYPTRA/WALLET_ADDRESS_INVALID',
  WALLET_CHAIN_UNSUPPORTED = 'CRYPTRA/WALLET_CHAIN_UNSUPPORTED',
  WALLET_SIGNATURE_REJECTED = 'CRYPTRA/WALLET_SIGNATURE_REJECTED',
  WALLET_SIGNATURE_INVALID = 'CRYPTRA/WALLET_SIGNATURE_INVALID',

  // Swap
  SWAP_QUOTE_FAILED = 'CRYPTRA/SWAP_QUOTE_FAILED',
  SWAP_QUOTE_EXPIRED = 'CRYPTRA/SWAP_QUOTE_EXPIRED',
  SWAP_SLIPPAGE_EXCEEDED = 'CRYPTRA/SWAP_SLIPPAGE_EXCEEDED',
  SWAP_EXECUTION_FAILED = 'CRYPTRA/SWAP_EXECUTION_FAILED',

  // Perpetuals
  PERP_ORDER_REJECTED = 'CRYPTRA/PERP_ORDER_REJECTED',
  PERP_INSUFFICIENT_MARGIN = 'CRYPTRA/PERP_INSUFFICIENT_MARGIN',
  PERP_LEVERAGE_INVALID = 'CRYPTRA/PERP_LEVERAGE_INVALID',
  PERP_VENUE_UNAVAILABLE = 'CRYPTRA/PERP_VENUE_UNAVAILABLE',

  // Fee / XP / Level / Referral
  FEE_CONFIG_INVALID = 'CRYPTRA/FEE_CONFIG_INVALID',
  XP_EVENT_INVALID = 'CRYPTRA/XP_EVENT_INVALID',
  REFERRAL_CODE_INVALID = 'CRYPTRA/REFERRAL_CODE_INVALID',
  REFERRAL_SELF_REFERRAL = 'CRYPTRA/REFERRAL_SELF_REFERRAL',
  REFERRAL_ALREADY_ACTIVE = 'CRYPTRA/REFERRAL_ALREADY_ACTIVE',
}

export type ErrorCode = keyof typeof ErrorCodes;

